name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw64/mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-libzip mingw64/mingw-w64-x86_64-make
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          make HAVE_LIBZIP=1 clean tests
