name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install xmllint
      run: sudo apt-get install -y libzip-dev
    - uses: actions/checkout@v4
    - name: make
      run: make HAVE_LIBZIP=1
    - name: make tests
      run: make HAVE_LIBZIP=1 tests
  build-win64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-libzip
    - name: Add MSYS2 to PATH
      run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
    - name: make
      run: make HAVE_LIBZIP=1
    - name: make tests
      run: make HAVE_LIBZIP=1 tests
